# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/stodgy/OS-MS2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/stodgy/OS-MS2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stodgy/OS-MS2/CMakeFiles /home/stodgy/OS-MS2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/stodgy/OS-MS2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OS_MS2

# Build rule for target.
OS_MS2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OS_MS2
.PHONY : OS_MS2

# fast build rule for target.
OS_MS2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/build
.PHONY : OS_MS2/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/main.c.s
.PHONY : main.c.s

memory.o: memory.c.o
.PHONY : memory.o

# target to build an object file
memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/memory.c.o
.PHONY : memory.c.o

memory.i: memory.c.i
.PHONY : memory.i

# target to preprocess a source file
memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/memory.c.i
.PHONY : memory.c.i

memory.s: memory.c.s
.PHONY : memory.s

# target to generate assembly for a file
memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/memory.c.s
.PHONY : memory.c.s

os.o: os.c.o
.PHONY : os.o

# target to build an object file
os.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/os.c.o
.PHONY : os.c.o

os.i: os.c.i
.PHONY : os.i

# target to preprocess a source file
os.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/os.c.i
.PHONY : os.c.i

os.s: os.c.s
.PHONY : os.s

# target to generate assembly for a file
os.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/os.c.s
.PHONY : os.c.s

pcb.o: pcb.c.o
.PHONY : pcb.o

# target to build an object file
pcb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/pcb.c.o
.PHONY : pcb.c.o

pcb.i: pcb.c.i
.PHONY : pcb.i

# target to preprocess a source file
pcb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/pcb.c.i
.PHONY : pcb.c.i

pcb.s: pcb.c.s
.PHONY : pcb.s

# target to generate assembly for a file
pcb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/pcb.c.s
.PHONY : pcb.c.s

schedulers/fcfs.o: schedulers/fcfs.c.o
.PHONY : schedulers/fcfs.o

# target to build an object file
schedulers/fcfs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/fcfs.c.o
.PHONY : schedulers/fcfs.c.o

schedulers/fcfs.i: schedulers/fcfs.c.i
.PHONY : schedulers/fcfs.i

# target to preprocess a source file
schedulers/fcfs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/fcfs.c.i
.PHONY : schedulers/fcfs.c.i

schedulers/fcfs.s: schedulers/fcfs.c.s
.PHONY : schedulers/fcfs.s

# target to generate assembly for a file
schedulers/fcfs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/fcfs.c.s
.PHONY : schedulers/fcfs.c.s

schedulers/mlfq.o: schedulers/mlfq.c.o
.PHONY : schedulers/mlfq.o

# target to build an object file
schedulers/mlfq.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/mlfq.c.o
.PHONY : schedulers/mlfq.c.o

schedulers/mlfq.i: schedulers/mlfq.c.i
.PHONY : schedulers/mlfq.i

# target to preprocess a source file
schedulers/mlfq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/mlfq.c.i
.PHONY : schedulers/mlfq.c.i

schedulers/mlfq.s: schedulers/mlfq.c.s
.PHONY : schedulers/mlfq.s

# target to generate assembly for a file
schedulers/mlfq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/mlfq.c.s
.PHONY : schedulers/mlfq.c.s

schedulers/queue.o: schedulers/queue.c.o
.PHONY : schedulers/queue.o

# target to build an object file
schedulers/queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/queue.c.o
.PHONY : schedulers/queue.c.o

schedulers/queue.i: schedulers/queue.c.i
.PHONY : schedulers/queue.i

# target to preprocess a source file
schedulers/queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/queue.c.i
.PHONY : schedulers/queue.c.i

schedulers/queue.s: schedulers/queue.c.s
.PHONY : schedulers/queue.s

# target to generate assembly for a file
schedulers/queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/queue.c.s
.PHONY : schedulers/queue.c.s

schedulers/round_robin.o: schedulers/round_robin.c.o
.PHONY : schedulers/round_robin.o

# target to build an object file
schedulers/round_robin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/round_robin.c.o
.PHONY : schedulers/round_robin.c.o

schedulers/round_robin.i: schedulers/round_robin.c.i
.PHONY : schedulers/round_robin.i

# target to preprocess a source file
schedulers/round_robin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/round_robin.c.i
.PHONY : schedulers/round_robin.c.i

schedulers/round_robin.s: schedulers/round_robin.c.s
.PHONY : schedulers/round_robin.s

# target to generate assembly for a file
schedulers/round_robin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/schedulers/round_robin.c.s
.PHONY : schedulers/round_robin.c.s

ui/dashboard.o: ui/dashboard.c.o
.PHONY : ui/dashboard.o

# target to build an object file
ui/dashboard.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/dashboard.c.o
.PHONY : ui/dashboard.c.o

ui/dashboard.i: ui/dashboard.c.i
.PHONY : ui/dashboard.i

# target to preprocess a source file
ui/dashboard.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/dashboard.c.i
.PHONY : ui/dashboard.c.i

ui/dashboard.s: ui/dashboard.c.s
.PHONY : ui/dashboard.s

# target to generate assembly for a file
ui/dashboard.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/dashboard.c.s
.PHONY : ui/dashboard.c.s

ui/log_and_console.o: ui/log_and_console.c.o
.PHONY : ui/log_and_console.o

# target to build an object file
ui/log_and_console.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/log_and_console.c.o
.PHONY : ui/log_and_console.c.o

ui/log_and_console.i: ui/log_and_console.c.i
.PHONY : ui/log_and_console.i

# target to preprocess a source file
ui/log_and_console.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/log_and_console.c.i
.PHONY : ui/log_and_console.c.i

ui/log_and_console.s: ui/log_and_console.c.s
.PHONY : ui/log_and_console.s

# target to generate assembly for a file
ui/log_and_console.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/log_and_console.c.s
.PHONY : ui/log_and_console.c.s

ui/memory_viewer.o: ui/memory_viewer.c.o
.PHONY : ui/memory_viewer.o

# target to build an object file
ui/memory_viewer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/memory_viewer.c.o
.PHONY : ui/memory_viewer.c.o

ui/memory_viewer.i: ui/memory_viewer.c.i
.PHONY : ui/memory_viewer.i

# target to preprocess a source file
ui/memory_viewer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/memory_viewer.c.i
.PHONY : ui/memory_viewer.c.i

ui/memory_viewer.s: ui/memory_viewer.c.s
.PHONY : ui/memory_viewer.s

# target to generate assembly for a file
ui/memory_viewer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/memory_viewer.c.s
.PHONY : ui/memory_viewer.c.s

ui/process_creation_and_config.o: ui/process_creation_and_config.c.o
.PHONY : ui/process_creation_and_config.o

# target to build an object file
ui/process_creation_and_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/process_creation_and_config.c.o
.PHONY : ui/process_creation_and_config.c.o

ui/process_creation_and_config.i: ui/process_creation_and_config.c.i
.PHONY : ui/process_creation_and_config.i

# target to preprocess a source file
ui/process_creation_and_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/process_creation_and_config.c.i
.PHONY : ui/process_creation_and_config.c.i

ui/process_creation_and_config.s: ui/process_creation_and_config.c.s
.PHONY : ui/process_creation_and_config.s

# target to generate assembly for a file
ui/process_creation_and_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/process_creation_and_config.c.s
.PHONY : ui/process_creation_and_config.c.s

ui/resource_management.o: ui/resource_management.c.o
.PHONY : ui/resource_management.o

# target to build an object file
ui/resource_management.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/resource_management.c.o
.PHONY : ui/resource_management.c.o

ui/resource_management.i: ui/resource_management.c.i
.PHONY : ui/resource_management.i

# target to preprocess a source file
ui/resource_management.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/resource_management.c.i
.PHONY : ui/resource_management.c.i

ui/resource_management.s: ui/resource_management.c.s
.PHONY : ui/resource_management.s

# target to generate assembly for a file
ui/resource_management.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/resource_management.c.s
.PHONY : ui/resource_management.c.s

ui/scheduler_control.o: ui/scheduler_control.c.o
.PHONY : ui/scheduler_control.o

# target to build an object file
ui/scheduler_control.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/scheduler_control.c.o
.PHONY : ui/scheduler_control.c.o

ui/scheduler_control.i: ui/scheduler_control.c.i
.PHONY : ui/scheduler_control.i

# target to preprocess a source file
ui/scheduler_control.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/scheduler_control.c.i
.PHONY : ui/scheduler_control.c.i

ui/scheduler_control.s: ui/scheduler_control.c.s
.PHONY : ui/scheduler_control.s

# target to generate assembly for a file
ui/scheduler_control.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/scheduler_control.c.s
.PHONY : ui/scheduler_control.c.s

ui/visualization_execution.o: ui/visualization_execution.c.o
.PHONY : ui/visualization_execution.o

# target to build an object file
ui/visualization_execution.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/visualization_execution.c.o
.PHONY : ui/visualization_execution.c.o

ui/visualization_execution.i: ui/visualization_execution.c.i
.PHONY : ui/visualization_execution.i

# target to preprocess a source file
ui/visualization_execution.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/visualization_execution.c.i
.PHONY : ui/visualization_execution.c.i

ui/visualization_execution.s: ui/visualization_execution.c.s
.PHONY : ui/visualization_execution.s

# target to generate assembly for a file
ui/visualization_execution.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OS_MS2.dir/build.make CMakeFiles/OS_MS2.dir/ui/visualization_execution.c.s
.PHONY : ui/visualization_execution.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OS_MS2"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... os.o"
	@echo "... os.i"
	@echo "... os.s"
	@echo "... pcb.o"
	@echo "... pcb.i"
	@echo "... pcb.s"
	@echo "... schedulers/fcfs.o"
	@echo "... schedulers/fcfs.i"
	@echo "... schedulers/fcfs.s"
	@echo "... schedulers/mlfq.o"
	@echo "... schedulers/mlfq.i"
	@echo "... schedulers/mlfq.s"
	@echo "... schedulers/queue.o"
	@echo "... schedulers/queue.i"
	@echo "... schedulers/queue.s"
	@echo "... schedulers/round_robin.o"
	@echo "... schedulers/round_robin.i"
	@echo "... schedulers/round_robin.s"
	@echo "... ui/dashboard.o"
	@echo "... ui/dashboard.i"
	@echo "... ui/dashboard.s"
	@echo "... ui/log_and_console.o"
	@echo "... ui/log_and_console.i"
	@echo "... ui/log_and_console.s"
	@echo "... ui/memory_viewer.o"
	@echo "... ui/memory_viewer.i"
	@echo "... ui/memory_viewer.s"
	@echo "... ui/process_creation_and_config.o"
	@echo "... ui/process_creation_and_config.i"
	@echo "... ui/process_creation_and_config.s"
	@echo "... ui/resource_management.o"
	@echo "... ui/resource_management.i"
	@echo "... ui/resource_management.s"
	@echo "... ui/scheduler_control.o"
	@echo "... ui/scheduler_control.i"
	@echo "... ui/scheduler_control.s"
	@echo "... ui/visualization_execution.o"
	@echo "... ui/visualization_execution.i"
	@echo "... ui/visualization_execution.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

